spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  redis:
    host: 192.168.56.101
    port: 6379
  jpa:
    show-sql: true
